
server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mkp_web?useSSL=true&serverTimezone=Asia/Bangkok
    username: root
    password: password
    auto-commit: true

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
